### ISSUE TITLE
TypeError: e.locizeLoaded.filter is not a function

### ISSUE THREAD

**Issue by DercilioFontes** [locize/next-i18next-locize#4]
## 🐛 Bug Report

I implemented `locize` in a React project already set with i18n, and I am getting this error with the Locize window blank.
It shows the login process to Locize, which is concluded and followed by the error. Maybe I am missing something, but I couldn't find any similar issue or something in the documentation.
```
main.691f02c2.js:2 TypeError: e.locizeLoaded.filter is not a function
    at main.691f02c2.js:2:3693861
    at Array.forEach (<anonymous>)
    at main.691f02c2.js:2:3693759
    at Array.forEach (<anonymous>)
    at main.691f02c2.js:2:3693631
    at Array.forEach (<anonymous>)
    at main.691f02c2.js:2:3693578
    at main.691f02c2.js:2:3694511
    at Dc (main.691f02c2.js:2:1355722)
    at t.unstable_runWithPriority (main.691f02c2.js:2:1595069)
```
![Screenshot 2024-11-05 at 9 58 38 PM](https://github.com/user-attachments/assets/86af83f7-2cf6-4524-8e28-98e58cc8b44b)

## To Reproduce
I can't share my repo. I hope I can have feedback on what I added. If required later, I can try to see if I can reproduce it in a small project.

```typescript
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-locize-backend';
import { locizeEditorPlugin } from 'locize';
import locizeLastUsed from 'locize-lastused';
import { initReactI18next } from 'react-i18next';

import en from './translations/en/translation.json';
import es from './translations/es/translation.json';
import fr from './translations/fr/translation.json';

const isLocal = process.env.MODE === 'development';

export const resources = {
  es: { translation: es },
  en: { translation: en },
  fr: { translation: fr },
} as const;

export type EnglishTranslation = (typeof resources)['en']['translation'];
type Namespace = keyof EnglishTranslation;
type Key = keyof EnglishTranslation[Namespace];

if (isLocal) {
  i18n.use(locizeLastUsed).init({
    locizeLastUsed: {
      projectId: 'projectId',
      apiKey: 'apiKey',
      referenceLng: 'en',
      version: 'latest',
      allowedHosts: ['localhost'],
    },
  });
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .use(Backend)
  .use(locizeEditorPlugin({ show: true }))
  .init({
    backend: {
      projectId: 'projectId',
      apiKey: 'apiKey',
      referenceLng: 'en',
      version: 'latest'
    },
    react: {
      bindI18n: 'languageChanged editorSaved',
    },
    returnNull: false,
    fallbackLng: 'en',
    supportedLngs:['en', 'fr', 'es'],
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    resources,
    debug: isLocal,
    parseMissingKeyHandler: (missingKey) => {
      const translation = resources[i18n.language as keyof typeof resources].translation as EnglishTranslation;
      const [namespace, key] = missingKey.split('.') as [Namespace, Key];
      const result = translation?.[namespace]?.[key];
      if (result) {
        return result;
      } else {
        console.error(new Error(`Missing translation for ${missingKey}.`));
        return missingKey;
      }
    },
  });

export default i18n;
```

```typescript
import React from 'react';
import { createRoot } from 'react-dom/client';
import { I18nextProvider } from 'react-i18next';
import { Provider } from 'react-redux';

import App from './App';
import i18n from './i18n';
import { store } from './store';

const container = document.getElementById('root');

if (container) {
  const root = createRoot(container);
  root.render(
    <React.StrictMode>
      <Provider store={store}>
        <I18nextProvider i18n={i18n}>
              <App />
        </I18nextProvider>
      </Provider>
    </React.StrictMode>,
  );
}
```

## Expected behavior

I expected the Locize window to show content and no error.

## Your Environment

    "i18next": "^23.16.4",
    "i18next-browser-languagedetector": "^8.0.0",
    "i18next-locize-backend": "^6.5.2",
    "locize": "^3.3.0",
    "locize-lastused": "^3.4.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "typescript": "^5.5.4",
    "vite": "^5.4.1",

- Development
- localhost
- Node v20.18.0
- Browser: Chrome Dev Version 132.0.6811.3 (Official Build) dev (arm64)
- OS: Mac M1 Max / macOS 15.1 (24B83)

**Comment by adrai** [comment]
Thank you Dercilio for the info...
You're right, since the last deployment, this could have happened in specific circumstances.
It should be fixed now, so can you retry again?

**Comment by DercilioFontes** [comment]
Hi @adrai 

It is working. I'll close the issue.

Thanks.
